// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NestedUnitTests
{
    internal sealed partial class Vsix
    {
        public const string Id = "NestedUnitTests.a2dc821e-8edc-4842-9da4-515cfcd19007";
        public const string Name = "Nested Unit Tests";
        public const string Description = @"What's about to move your unit tests closer to the code?";
        public const string Language = "en-US";
        public const string Version = "0.4";
        public const string Author = "lsoft";
        public const string Tags = "";
    }
}
