// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NestedUnitTests
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string logo_16_galleryString = "7c4e9e67-a0a2-4765-8b77-7f11033fdafd";
        public static Guid logo_16_gallery = new Guid(logo_16_galleryString);

        public const string NestedUnitTestsString = "2853c238-e3a4-48b9-ad54-234807d8b2d3";
        public static Guid NestedUnitTests = new Guid(NestedUnitTestsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int logo_16 = 0x0001;
        public const int PrepareSdkProjectMenuGroup = 0x8821;
        public const int PrepareSdkProjectCommandId = 0x8921;
        public const int AddFileMenuGroup = 0x8822;
        public const int AddFileCommandId = 0x8922;
    }
}