// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NestedUnitTests
{
    internal sealed partial class Vsix
    {
        public const string Id = "NestedUnitTests.a2dc821e-8edc-4842-9da4-515cfcd19006";
        public const string Name = "NestedUnitTests";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "ls";
        public const string Tags = "";
    }
}
